# Use root/example as user/password credentials
version: '3.1'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: administrator
      MONGO_INITDB_ROOT_PASSWORD: '@teste15'
    ports:
      - 27017:27017
