version: '3.1'
services:
  mongo:
    image: mongo
    hostname: ovigia-db
    container_name: ovigia-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=ovigia
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=1234
    #command: bash -c "mongod && sleep 10 && mongo --eval 'db.createCollection(\"mensalidade\")'"

