logging.level.web: INFO
#spring.data.mongodb.uri: mongodb://172.18.0.1:27017/ovigia

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring.data.mongodb:
  host: 127.0.0.1
  port: 27017
  database: ovigia

spring:
  codec:
    max-in-memory-size: 15MB