logging.level.web: INFO

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  codec:
    max-in-memory-size: 15MB
  data:
    mongodb:
     uri: mongodb://admin:1234@localhost:27017/ovigia


# database imple values: HASH, MONGO
database:
  impl: MONGO

