logging.level.web: INFO
spring.data.mongodb.uri: mongodb://localhost:27017/ovigia
#spring.data.mongodb.uri: mongodb://167.114.185.231:27017/ovigia

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  codec:
    max-in-memory-size: 15MB